#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a radicale
sudo yunohost app setting radicale skipped_uris -v "$path"
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check depends installation
sudo apt-get install -y python-pip python-virtualenv python-dev libldap2-dev libsasl2-dev libssl-dev uwsgi uwsgi-plugin-python

# Init virtualenv
sudo virtualenv /usr/local/radicale
sudo bash -c "source /usr/local/radicale/bin/activate && pip install radicale python-ldap"

#Configuration Radicale
if [ ! -d /etc/radicale ];
then
	sudo mkdir /etc/radicale
fi
sudo cp ../conf/config /etc/radicale/
sudo cp ../conf/logging /etc/radicale/

# Copy files to the right place
final_path=/var/www/radicale
sudo mkdir -p $final_path
sudo cp ../conf/radicale.wsgi $final_path
sudo mkdir -p /home/yunohost.app/radicale/collections

# Set permissions to radicale directory
sudo chown -R www-data. $final_path
sudo chown -R www-data. /home/yunohost.app/radicale/collections
sudo touch /var/log/radicale
sudo chgrp www-data /var/log/radicale
sudo chmod g+w /var/log/radicale

# Copy uwsgi config
sudo cp ../conf/radicale.ini /etc/uwsgi/apps-available/
sudo ln -s /etc/uwsgi/apps-available/radicale.ini /etc/uwsgi/apps-enabled/

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/radicale.conf

# Fix permission
sudo chmod 755 /etc/radicale/
sudo find /usr/local/radicale/ -type d -exec chmod 2755 {} \;
sudo find /usr/local/radicale/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/radicale/*

## Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo service uwsgi restart
sudo yunohost app setting radicale skipped_uris -v "/"
sudo yunohost app ssowatconf
