#!/bin/bash

# Get app settings
domain=$(sudo yunohost app setting radicale domain)
path=$(sudo yunohost app setting radicale path)

# Check depends installation
sudo apt-get install -y python-pip python-virtualenv python-dev libldap2-dev libsasl2-dev libssl-dev uwsgi uwsgi-plugin-python

if [ -d /usr/local/radicale ];
then
  sudo mkdir -p /opt/yunohost
  sudo mv /usr/local/radicale /opt/yunohost/
fi

# Set permissions to radicale directory
sudo grep radicaled /etc/passwd  > /dev/null 2>&1
if [ $? != 0 ];
then
  sudo useradd radicale -d /opt/yunohost/radicale
fi
sudo chown radicale:radicale -R /opt/yunohost/radicale

# Upgrade pip packages
sudo rm -Rf /opt/yunohost/radicale
sudo virtualenv /opt/yunohost/radicale
sudo bash -c 'source /opt/yunohost/radicale/bin/activate && pip install radicale==1.0.1 python-ldap'

# Radicale configuration
sudo cp ../conf/config /etc/radicale/
sudo cp ../conf/logging /etc/radicale/
sudo cp ../conf/rights /etc/radicale/
sudo sed -i "s@CHANGEPATH@$path@g" /etc/radicale/config

# Copy files to the right place
final_path=/var/www/radicale
sudo mkdir -p $final_path/collections
sudo chown radicale:www-data -R $final_path
sudo cp ../conf/radicale.wsgi $final_path

# Copy uwsgi config
sudo cp ../conf/radicale.ini /etc/uwsgi/apps-available/

# Update nginx config
sudo find /etc/nginx/conf.d/ -name radicale.conf -exec sed -i 's@tmp\/radicale.sock@run\/uwsgi\/app\/radicale\/socket@' {} \;

# Fix permission
sudo chmod 755 /etc/radicale/
sudo find /opt/yunohost/radicale/ -type d -exec chmod 2755 {} \;
sudo find /opt/yunohost/radicale/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/radicale/*
sudo chown -R radicale $final_path
sudo touch /var/log/radicale
sudo chgrp radicale /var/log/radicale
sudo chmod g+w /var/log/radicale

sudo yunohost app setting radicale skipped_uris -v "/"
sudo yunohost app ssowatconf
sudo service uwsgi stop
sudo killall uwsgi 
sudo service uwsgi start
sudo service nginx reload
